# Generated by Django 4.0.1 on 2022-02-07 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentsmodel',
            name='hates_user',
            field=models.ManyToManyField(blank=True, related_name='hates_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentsmodel',
            name='likes_user',
            field=models.ManyToManyField(blank=True, related_name='likes_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentscomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentscomment',
            name='contents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.contentsmodel'),
        ),
    ]
