# Generated by Django 4.0.1 on 2022-02-09 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
        ('contents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentscomment',
            name='contents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.store'),
        ),
    ]
