# Generated by Django 4.0.1 on 2022-02-07 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentscomment',
            name='cmt_hates_user',
            field=models.ManyToManyField(blank=True, related_name='cmt_hates_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentscomment',
            name='cmt_likes_user',
            field=models.ManyToManyField(blank=True, related_name='cmt_likes_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
