# Generated by Django 4.0.1 on 2022-02-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_savesubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='savesubcategory',
            name='stores',
            field=models.TextField(null=True),
        ),
    ]
