# Generated by Django 4.0.1 on 2022-02-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_usermodel_like_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='like_food',
            field=models.TextField(default=''),
        ),
    ]
